# Generated by Django 4.0.3 on 2022-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_page_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
                ('num_replies', models.IntegerField(default=0)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
